-- 서재교회 홈페이지 Supabase 초기 설정
-- Supabase > SQL Editor 에서 이 파일 전체를 한 번 실행하세요.

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  church_name text not null default '서재교회',
  slogan text default '하나님의 사랑과 은혜로 생명을 살리는 서재교회',
  pastor_name text default '담임목사 천성일',
  associate_pastor text default '부목사 천길진',
  elder_name text default '장로 이병욱',
  denomination text default '대한예수교장로회',
  founded_date text default '1985. 4. 22.',
  hero_title text default '예수님을 닮아 사랑으로 섬기는 교회',
  hero_text text default '하나님의 사랑과 은혜로 생명을 살리며 말씀과 기도로 지역을 섬기는 서재교회입니다.',
  address text default '대구시 달성군 다사읍 서재로 104 · 서재초등학교 앞',
  phone text default '053-585-3608 · 010-2254-3608',
  youtube_url text default '',
  map_url text default 'https://www.google.com/maps/search/?api=1&query=%EB%8C%80%EA%B5%AC%EC%8B%9C%20%EB%8B%AC%EC%84%B1%EA%B5%B0%20%EB%8B%A4%EC%82%AC%EC%9D%8D%20%EC%84%9C%EC%9E%AC%EB%A1%9C%20104',
  sunday_service text default '주일 1부예배 오전 11:00',
  sunday_afternoon_service text default '주일 오후예배 오후 2:00',
  sunday_school_service text default '주일학교 오전 9:30',
  youth_service text default '중고등부 오후 2:00',
  wednesday_service text default '수요예배 오후 7:30',
  friday_service text default '금요예배 오후 7:30',
  dawn_service text default '새벽예배 오전 5:30',
  bus_routes text default '405, 504, 509, 523, 725, 급행7, 성서3, 성서1-1',
  updated_at timestamptz default now()
);

-- 기존 V1 테이블이 이미 있다면 새 열을 안전하게 추가합니다.
alter table public.site_settings add column if not exists associate_pastor text default '부목사 천길진';
alter table public.site_settings add column if not exists elder_name text default '장로 이병욱';
alter table public.site_settings add column if not exists denomination text default '대한예수교장로회';
alter table public.site_settings add column if not exists founded_date text default '1985. 4. 22.';
alter table public.site_settings add column if not exists sunday_afternoon_service text default '주일 오후예배 오후 2:00';
alter table public.site_settings add column if not exists sunday_school_service text default '주일학교 오전 9:30';
alter table public.site_settings add column if not exists youth_service text default '중고등부 오후 2:00';
alter table public.site_settings add column if not exists friday_service text default '금요예배 오후 7:30';
alter table public.site_settings add column if not exists bus_routes text default '405, 504, 509, 523, 725, 급행7, 성서3, 성서1-1';

create table if not exists public.sermons (
  id bigint generated by default as identity primary key,
  title text not null, scripture text not null, preacher text not null,
  youtube_url text default '', service_date date not null,
  created_at timestamptz default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null, body text not null, published_at date not null,
  created_at timestamptz default now()
);

create table if not exists public.bulletins (
  id bigint generated by default as identity primary key,
  title text not null, service_date date not null, file_url text not null,
  storage_path text, created_at timestamptz default now()
);

insert into public.site_settings(id,church_name,slogan,pastor_name,associate_pastor,elder_name,denomination,founded_date,hero_title,hero_text,address,phone,youtube_url,map_url,sunday_service,sunday_afternoon_service,sunday_school_service,youth_service,wednesday_service,friday_service,dawn_service,bus_routes)
values (1,'서재교회','하나님의 사랑과 은혜로 생명을 살리는 서재교회','담임목사 천성일','부목사 천길진','장로 이병욱','대한예수교장로회','1985. 4. 22.','예수님을 닮아 사랑으로 섬기는 교회','하나님의 사랑과 은혜로 생명을 살리며 말씀과 기도로 지역을 섬기는 서재교회입니다.','대구시 달성군 다사읍 서재로 104 · 서재초등학교 앞','053-585-3608 · 010-2254-3608','','https://www.google.com/maps/search/?api=1&query=%EB%8C%80%EA%B5%AC%EC%8B%9C%20%EB%8B%AC%EC%84%B1%EA%B5%B0%20%EB%8B%A4%EC%82%AC%EC%9D%8D%20%EC%84%9C%EC%9E%AC%EB%A1%9C%20104','주일 1부예배 오전 11:00','주일 오후예배 오후 2:00','주일학교 오전 9:30','중고등부 오후 2:00','수요예배 오후 7:30','금요예배 오후 7:30','새벽예배 오전 5:30','405, 504, 509, 523, 725, 급행7, 성서3, 성서1-1')
on conflict (id) do update set
church_name=excluded.church_name,slogan=excluded.slogan,pastor_name=excluded.pastor_name,
associate_pastor=excluded.associate_pastor,elder_name=excluded.elder_name,denomination=excluded.denomination,
founded_date=excluded.founded_date,hero_title=excluded.hero_title,hero_text=excluded.hero_text,
address=excluded.address,phone=excluded.phone,map_url=excluded.map_url,
sunday_service=excluded.sunday_service,sunday_afternoon_service=excluded.sunday_afternoon_service,
sunday_school_service=excluded.sunday_school_service,youth_service=excluded.youth_service,
wednesday_service=excluded.wednesday_service,friday_service=excluded.friday_service,
dawn_service=excluded.dawn_service,bus_routes=excluded.bus_routes,updated_at=now();

alter table public.site_settings enable row level security;
alter table public.sermons enable row level security;
alter table public.notices enable row level security;
alter table public.bulletins enable row level security;

drop policy if exists "public read settings" on public.site_settings;
drop policy if exists "public read sermons" on public.sermons;
drop policy if exists "public read notices" on public.notices;
drop policy if exists "public read bulletins" on public.bulletins;
drop policy if exists "auth write settings" on public.site_settings;
drop policy if exists "auth write sermons" on public.sermons;
drop policy if exists "auth write notices" on public.notices;
drop policy if exists "auth write bulletins" on public.bulletins;

create policy "public read settings" on public.site_settings for select using (true);
create policy "public read sermons" on public.sermons for select using (true);
create policy "public read notices" on public.notices for select using (true);
create policy "public read bulletins" on public.bulletins for select using (true);
create policy "auth write settings" on public.site_settings for all to authenticated using (true) with check (true);
create policy "auth write sermons" on public.sermons for all to authenticated using (true) with check (true);
create policy "auth write notices" on public.notices for all to authenticated using (true) with check (true);
create policy "auth write bulletins" on public.bulletins for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('bulletins', 'bulletins', true)
on conflict (id) do update set public = true;

drop policy if exists "public bulletin read" on storage.objects;
drop policy if exists "auth bulletin insert" on storage.objects;
drop policy if exists "auth bulletin update" on storage.objects;
drop policy if exists "auth bulletin delete" on storage.objects;
create policy "public bulletin read" on storage.objects for select using (bucket_id='bulletins');
create policy "auth bulletin insert" on storage.objects for insert to authenticated with check (bucket_id='bulletins');
create policy "auth bulletin update" on storage.objects for update to authenticated using (bucket_id='bulletins') with check (bucket_id='bulletins');
create policy "auth bulletin delete" on storage.objects for delete to authenticated using (bucket_id='bulletins');

-- 초기 자료는 중복 방지를 위해 없는 경우에만 넣습니다.
insert into public.sermons(title,scripture,preacher,youtube_url,service_date)
select '주 안에서','빌립보서 4:4-6','인도자','','2026-08-30'
where not exists (select 1 from public.sermons where title='주 안에서' and service_date='2026-08-30');

insert into public.sermons(title,scripture,preacher,youtube_url,service_date)
select '때','요한복음 7:25-30','인도자','','2026-08-30'
where not exists (select 1 from public.sermons where title='때' and service_date='2026-08-30');

insert into public.notices(title,body,published_at)
select '8월 30일 오후예배 안내','이번 주 오후예배는 오후 2시 30분에 드립니다.','2026-08-30'
where not exists (select 1 from public.notices where title='8월 30일 오후예배 안내' and published_at='2026-08-30');

insert into public.notices(title,body,published_at)
select '오후예배 후 공동의회','오후예배 후 공동의회가 있습니다. 의제는 위임목사 초빙건입니다.','2026-08-30'
where not exists (select 1 from public.notices where title='오후예배 후 공동의회' and published_at='2026-08-30');
