-- Supabase SQL Editor에서 이 파일 전체를 한 번 실행하세요.

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  church_name text not null default '샘플교회',
  slogan text default '말씀으로 세워지고 사랑으로 섬기는 교회',
  pastor_name text default '담임목사 홍길동',
  hero_title text default '하나님을 예배하고 이웃을 사랑합니다',
  hero_text text default '처음 방문하신 분도 편안하게 예배드릴 수 있도록 안내해 드립니다.',
  address text default '', phone text default '', youtube_url text default '', map_url text default '',
  sunday_service text default '주일 오전 11:00',
  wednesday_service text default '수요예배 오후 7:30',
  dawn_service text default '새벽기도회 오전 5:30',
  updated_at timestamptz default now()
);

create table if not exists public.sermons (
  id bigint generated by default as identity primary key,
  title text not null, scripture text not null, preacher text not null,
  youtube_url text not null, service_date date not null,
  created_at timestamptz default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null, body text not null, published_at date not null,
  created_at timestamptz default now()
);

create table if not exists public.bulletins (
  id bigint generated by default as identity primary key,
  title text not null, service_date date not null, file_url text not null,
  storage_path text, created_at timestamptz default now()
);

insert into public.site_settings(id) values (1) on conflict (id) do nothing;

alter table public.site_settings enable row level security;
alter table public.sermons enable row level security;
alter table public.notices enable row level security;
alter table public.bulletins enable row level security;

-- 누구나 홈페이지 내용을 읽을 수 있습니다.
create policy "public read settings" on public.site_settings for select using (true);
create policy "public read sermons" on public.sermons for select using (true);
create policy "public read notices" on public.notices for select using (true);
create policy "public read bulletins" on public.bulletins for select using (true);

-- 로그인한 사용자만 관리자 쓰기 작업 가능.
create policy "auth write settings" on public.site_settings for all to authenticated using (true) with check (true);
create policy "auth write sermons" on public.sermons for all to authenticated using (true) with check (true);
create policy "auth write notices" on public.notices for all to authenticated using (true) with check (true);
create policy "auth write bulletins" on public.bulletins for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('bulletins', 'bulletins', true)
on conflict (id) do update set public = true;

create policy "public bulletin read" on storage.objects for select using (bucket_id='bulletins');
create policy "auth bulletin insert" on storage.objects for insert to authenticated with check (bucket_id='bulletins');
create policy "auth bulletin update" on storage.objects for update to authenticated using (bucket_id='bulletins') with check (bucket_id='bulletins');
create policy "auth bulletin delete" on storage.objects for delete to authenticated using (bucket_id='bulletins');
