"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getBrowserClient } from "../../lib/supabase";

const blankSettings:any={church_name:"",slogan:"",pastor_name:"",associate_pastor:"",elder_name:"",denomination:"",founded_date:"",hero_title:"",hero_text:"",address:"",phone:"",youtube_url:"",map_url:"",sunday_service:"",sunday_afternoon_service:"",sunday_school_service:"",youth_service:"",wednesday_service:"",friday_service:"",dawn_service:"",bus_routes:""};

export default function Admin(){
 const router=useRouter(); const [ready,setReady]=useState(false); const [msg,setMsg]=useState(""); const [settings,setSettings]=useState<any>(blankSettings); const [sermons,setSermons]=useState<any[]>([]); const [notices,setNotices]=useState<any[]>([]); const [bulletins,setBulletins]=useState<any[]>([]);
 const sb=getBrowserClient();
 useEffect(()=>{(async()=>{if(!sb){setMsg("Supabase 환경변수가 없습니다. DEPLOY_GUIDE_KO.md를 확인하세요.");setReady(true);return;} const {data:{session}}=await sb.auth.getSession(); if(!session){router.replace("/admin/login");return;} await load(); setReady(true);})();},[]);
 async function load(){if(!sb)return; const [a,b,c,d]=await Promise.all([sb.from("site_settings").select("*").eq("id",1).maybeSingle(),sb.from("sermons").select("*").order("service_date",{ascending:false}),sb.from("notices").select("*").order("published_at",{ascending:false}),sb.from("bulletins").select("*").order("service_date",{ascending:false})]); if(a.data)setSettings({...blankSettings,...a.data}); setSermons(b.data||[]);setNotices(c.data||[]);setBulletins(d.data||[]);}
 async function saveSettings(e:FormEvent){e.preventDefault();if(!sb)return;const {error}=await sb.from("site_settings").upsert({id:1,...settings,updated_at:new Date().toISOString()});setMsg(error?error.message:"교회 기본정보를 저장했습니다.");}
 async function addSermon(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!sb)return;const f=new FormData(e.currentTarget);const row={title:f.get("title"),scripture:f.get("scripture"),preacher:f.get("preacher"),youtube_url:f.get("youtube_url")||"",service_date:f.get("service_date")};const {error}=await sb.from("sermons").insert(row);setMsg(error?error.message:"설교를 등록했습니다.");if(!error){e.currentTarget.reset();await load();}}
 async function addNotice(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!sb)return;const f=new FormData(e.currentTarget);const row={title:f.get("title"),body:f.get("body"),published_at:f.get("published_at")};const {error}=await sb.from("notices").insert(row);setMsg(error?error.message:"소식을 등록했습니다.");if(!error){e.currentTarget.reset();await load();}}
 async function addBulletin(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!sb)return;const f=new FormData(e.currentTarget);const file=f.get("file") as File; if(!file?.size){setMsg("주보 파일을 선택해 주세요.");return;} const path=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`; const up=await sb.storage.from("bulletins").upload(path,file,{contentType:file.type||"application/pdf"}); if(up.error){setMsg(up.error.message);return;} const {data:url}=sb.storage.from("bulletins").getPublicUrl(path); const {error}=await sb.from("bulletins").insert({title:f.get("title"),service_date:f.get("service_date"),file_url:url.publicUrl,storage_path:path});setMsg(error?error.message:"주보를 등록했습니다.");if(!error){e.currentTarget.reset();await load();}}
 async function del(table:string,id:number,storagePath?:string){if(!sb||!confirm("정말 삭제하시겠습니까?"))return;if(storagePath)await sb.storage.from("bulletins").remove([storagePath]);const {error}=await sb.from(table).delete().eq("id",id);setMsg(error?error.message:"삭제했습니다.");if(!error)await load();}
 async function logout(){if(sb)await sb.auth.signOut();router.push("/admin/login");}
 if(!ready)return <div className="admin-shell">관리자 정보를 확인하고 있습니다.</div>;
 return <div className="admin-shell"><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><h1>홈페이지 관리자</h1><p className="section-lead">교회 기본정보와 설교, 주보, 교회소식을 관리합니다.</p></div><button className="btn danger" onClick={logout}>로그아웃</button></div>{msg&&<div className="status">{msg}</div>}
 <div className="spacer"/><section className="card"><h2>교회 기본정보</h2><form className="form" onSubmit={saveSettings}>{Object.entries({church_name:"교회 이름",slogan:"교회 표어",pastor_name:"담임목사",associate_pastor:"부목사",elder_name:"장로",denomination:"교단",founded_date:"설립일",hero_title:"메인 제목",hero_text:"메인 설명",address:"주소",phone:"전화번호",youtube_url:"YouTube 주소",map_url:"지도 주소",sunday_service:"주일 1부예배",sunday_afternoon_service:"주일 오후예배",sunday_school_service:"주일학교",youth_service:"중고등부",wednesday_service:"수요예배",friday_service:"금요예배",dawn_service:"새벽예배",bus_routes:"버스 노선"}).map(([k,label])=><label key={k}>{label}<input value={settings[k]||""} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}<button className="btn" type="submit">기본정보 저장</button></form></section>
 <div className="spacer"/><div className="grid two"><section className="card"><h2>설교 등록</h2><form className="form" onSubmit={addSermon}><input name="title" placeholder="설교 제목" required/><input name="scripture" placeholder="본문 예: 요한복음 3:16" required/><input name="preacher" placeholder="설교자" required/><input name="youtube_url" type="url" placeholder="YouTube 주소 (없으면 비워도 됩니다)"/><input name="service_date" type="date" required/><button className="btn">설교 등록</button></form></section><section className="card"><h2>교회소식 등록</h2><form className="form" onSubmit={addNotice}><input name="title" placeholder="제목" required/><textarea name="body" placeholder="내용" required/><input name="published_at" type="date" required/><button className="btn">소식 등록</button></form></section></div>
 <div className="spacer"/><section className="card"><h2>주보 등록</h2><form className="form" onSubmit={addBulletin}><input name="title" placeholder="예: 2026년 8월 30일 주보" required/><input name="service_date" type="date" required/><input name="file" type="file" accept=".pdf,.ppt,.pptx,application/pdf,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation" required/><button className="btn">주보 업로드</button></form></section>
 <div className="spacer"/><section className="card"><h2>등록 자료 관리</h2><h3>설교</h3><div className="list">{sermons.map(x=><div className="list-row" key={x.id}><span>{x.service_date} · {x.title}</span><button className="btn danger" onClick={()=>del("sermons",x.id)}>삭제</button></div>)}</div><h3>교회소식</h3><div className="list">{notices.map(x=><div className="list-row" key={x.id}><span>{x.published_at} · {x.title}</span><button className="btn danger" onClick={()=>del("notices",x.id)}>삭제</button></div>)}</div><h3>주보</h3><div className="list">{bulletins.map(x=><div className="list-row" key={x.id}><span>{x.service_date} · {x.title}</span><button className="btn danger" onClick={()=>del("bulletins",x.id,x.storage_path)}>삭제</button></div>)}</div></section></div>
}
